### ISSUE TITLE
Alert stays visible

### ISSUE THREAD

**Issue by cyberdude** [vuejs-pt/vue-alert#1]
Hi!

I like this plugin but it seems that the alert stays visible after alerting the user with some information. It fades out and then the start alert-info mode is there with an empty message. Is this by design?

**Comment by davidpicarra** [comment]
Hi @cyberdude 
Are you referring to the demo or your own integration?
It is possible to set the default message that will show up after the timeout occurs for the alert you are showing. If you don't set any default (don't execute `this.$alert.setDefault()`) then the alert-info won't show up and instead the alert will disappear completely after the timeout
I'll update the demo

**Comment by cyberdude** [comment]
Hey David.

This is happening in my own integration with no defaults set. :(

**Comment by davidpicarra** [comment]
Hey @cyberdude 
I've set the default of this plugin to always hide unless you specifically call `this.$alert.setDefault`. Please download the latest version `1.1.1` and see if it works correctly on your side :)

**Comment by cyberdude** [comment]
Awesome! Thanks. Working beautifully!
