### ISSUE TITLE
error when try to import vue-alert

### ISSUE THREAD

**Issue by dexterns88** [vuejs-pt/vue-alert#2]
I getting error when try to load vue-alert as it explained in example:
`
import VueAlert from 'vue-alert'
`
ERROR in ./src/main.js
Module not found: Error: Can't resolve 'vue-alert' in '/var/www/d8-play/themes/vue/vueapp/src'

When I change import into
`
import VueAlert from '@vuejs-pt/vue-alert'
`
Everything works well.

Did I miss something, or it's wrong import in the documentation?

**Comment by davidpicarra** [comment]
Hi @dexterns88 

You are correct, it should be `import VueAlert from '@vuejs-pt/vue-alert'`.
I'm updating the documentation, sorry for the error.

**Comment by davidpicarra** [comment]
Documentation updated: 580fd66b74b4dbd26e9ae72e4be6599d9319e02e
