### ISSUE TITLE
Error when I try to import vue-alert

### ISSUE THREAD

**Issue by KittyCode** [vuejs-pt/vue-alert#3]
I'm getting error when I add " Vue.use(VueAlert) " into main.js:

index.js?a811:1 Uncaught TypeError: Cannot set property $alert of #<Vue$3> which has only a getter
    at Object.Bt [as install] (index.js?a811:1)
    at Function.Vue.use (vue.esm.js?efeb:4670)
    at eval (main.js?3479:15)
    at Object../src/main.js (app.js:1340)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at Object.0 (app.js:1357)
    at __webpack_require__ (app.js:679)
    at app.js:725
    at app.js:728

Did I miss something?

**Comment by davidpicarra** [comment]
Hi @KittyCode 
Can you share a full example for this error? Haven't seen this before while using the plugin

**Comment by KittyCode** [comment]
Hi @davidpicarra 
I think there is maybe some conflict with my project. 
Because today I installed a new project, and follow your documentation to install the plugin to the new project, and it worked fine. 
So I will check with my project.

Thank you!

**Comment by davidpicarra** [comment]
No worries, please let me know when you find the cause of this issue, could be something I can add on the plugin so it won't happen to other people

**Comment by dschoeni** [comment]
Could be a problem with http://element.eleme.io/ that uses the same hook for their alerts. Changing the import order fixes it:

```
// Element UI
Vue.use(ElementUI, { i18n: (key, value) => i18n.t(key, value) })

// Alert
Vue.use(VueAlert)
```

**Comment by davidpicarra** [comment]
@dschoeni thanks for the info! I'll look into it, I've managed to replicate the issue on my side with the `element-ui` library.

EDIT: looking closely at the error, this is an error from the `element-ui` library when trying to set the `Vue.$alert` so the solution that @dschoeni suggested makes sense, which would overwrite the Element UI alert functionality. 
<img width="622" alt="element-ui- alert" src="https://user-images.githubusercontent.com/5445369/34618735-9a313cbc-f237-11e7-8f0e-47ebed57447b.png">
